"""change candidate back to candidates

Revision ID: 37e0fa49635d
Revises: 820b26ef4c56
Create Date: 2021-05-17 19:24:00.107581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e0fa49635d'
down_revision = '820b26ef4c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    op.drop_constraint(None, 'opponent', type_='foreignkey')
    op.create_foreign_key(None, 'opponent', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opponent', type_='foreignkey')
    op.create_foreign_key(None, 'opponent', 'candidate', ['candidate_id'], ['id'])
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('win', sa.INTEGER(), nullable=True),
    sa.Column('loss', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
